-- MySQL Script generated by MySQL Workbench
-- Mon May  1 16:22:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userID` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `participationCounter` INT NOT NULL,
  `hostCounter` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `ageRange` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InputPosition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InputPosition` (
  `inputID` INT NOT NULL,
  `x-pos` INT NOT NULL,
  `y-pos` INT NOT NULL,
  PRIMARY KEY (`inputID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `eventID` INT NOT NULL,
  `eventName` VARCHAR(45) NOT NULL,
  `leader` INT NOT NULL,
  `date` DATE NOT NULL,
  `startTime` VARCHAR(45) NOT NULL,
  `endTime` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `minCapacity` INT NULL,
  `maxCapacity` INT NULL,
  `place` INT NOT NULL,
  `inputID` INT NULL,
  `visibility` INT NOT NULL,
  `numberOfRegistrations` INT NOT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `leader_idx` (`leader` ASC),
  INDEX `inputID_idx` (`inputID` ASC),
  CONSTRAINT `leader`
    FOREIGN KEY (`leader`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inputID`
    FOREIGN KEY (`inputID`)
    REFERENCES `mydb`.`InputPosition` (`inputID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participation` (
  `eventID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `eventID`
    FOREIGN KEY (`eventID`)
    REFERENCES `mydb`.`Event` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
